#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

[ -d src/flanterm ] || git clone https://github.com/mintsuki/flanterm.git src/flanterm

AUTOMAKE_LIBDIR="$(automake --print-libdir)"
cp "${AUTOMAKE_LIBDIR}/INSTALL" ./
mkdir -p build-aux
cp "${AUTOMAKE_LIBDIR}/install-sh" build-aux/

autoreconf -fvi -Wall
